/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Command */
        post: operations["submit_command_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_api_leads__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Events */
        get: operations["get_lead_events_api_leads__id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Proposal */
        post: operations["apply_proposal_api_proposals__proposal_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Proposal */
        post: operations["dismiss_proposal_api_proposals__proposal_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver Reply */
        post: operations["deliver_reply_api_replies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver Fixture Replies */
        post: operations["deliver_fixture_replies_api_replies_fixtures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_run_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionPlan
         * @description The plan of section 9.6. The plan hash (A.4) is taken over `model_dump(mode="json")`, so
         *     equal plans hold every list in one stable order.
         */
        ActionPlan: {
            /**
             * Catalogue Questions
             * @default []
             */
            catalogue_questions: string[];
            /**
             * Declines On Every Branch
             * @default []
             */
            declines_on_every_branch: components["schemas"]["RuleTrace"][];
            /**
             * Effects
             * @default []
             */
            effects: components["schemas"]["PlannedEffect"][];
            /**
             * Not Evaluated
             * @default []
             */
            not_evaluated: components["schemas"]["NotEvaluatedNote"][];
            /**
             * Open Choices
             * @default []
             */
            open_choices: components["schemas"]["OpenChoice"][];
            /**
             * Proposed Decline
             * @default false
             */
            proposed_decline: boolean;
            /**
             * Undecided
             * @default []
             */
            undecided: components["schemas"]["UndecidedPage"][];
            /** Underwriter Decline */
            underwriter_decline: string | null;
        };
        /** AdvisoryEffect */
        AdvisoryEffect: {
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /** Rule */
            rule: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "advisory";
        };
        /**
         * AnswerEvent
         * @description The turn closed with an answer. A directive the command layer refuses (an approval, a
         *     rejection, a send) closes this way too, with the reason and no card (7.4, A.11).
         */
        AnswerEvent: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "answer";
        };
        /** ApproveCommand */
        ApproveCommand: {
            payload: components["schemas"]["ApprovePayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approve";
        };
        /** ApprovePayload */
        ApprovePayload: {
            /**
             * Artifact Hash
             * @description The payload hash shown with the draft. Required when the item is a draft or a review that holds a draft, and omitted otherwise. Which item it is, is known to the handler, so the schema leaves the field optional.
             */
            artifact_hash?: string | null;
            /** Item Id */
            item_id: number;
            /** Reason */
            reason: string;
        };
        /**
         * Assumption
         * @description One unknown input and the case taken for it, in A.6's condition form.
         */
        Assumption: {
            /** Field */
            field: string;
            /** When */
            when: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * BlockerDetail
         * @description What a blocker carries beyond its kind and owner; also the shape of `blockers.detail_json`.
         */
        BlockerDetail: {
            /** Cause */
            cause: ("late_reply" | "unread_reply" | "off_topic_reply" | "declining_reply" | "reply_after_terminal_status" | "round_limit" | "identity_score_missing" | "identity_score_unsupported") | null;
            /**
             * Cause Persists
             * @default false
             */
            cause_persists: boolean;
            /**
             * Choice Ids
             * @default []
             */
            choice_ids: string[];
            /** Intent Id */
            intent_id: string | null;
            /** Item Kind */
            item_kind: ("draft" | "observation" | "delivery_unknown" | "no_contact_route" | "review") | null;
            /** Observation Id */
            observation_id: number | null;
            /** Resume Trigger */
            resume_trigger: string;
            /** Text */
            text: string;
        };
        /**
         * BlockerView
         * @description An open blocker. `item_id` is `blockers.id`, the id an `approve` or `reject` names.
         *
         *     The conversation offers the actions for every open item (section 11), so the blocker carries
         *     what its action needs: a pending observation's value (`observation`, required exactly for the
         *     item kind `observation`). The item kind and, for a review, the cause are in `detail`.
         */
        BlockerView: {
            detail: components["schemas"]["BlockerDetail"];
            /** Item Id */
            item_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "delivery_unknown" | "underwriter_question" | "underwriter_review" | "data" | "producer_reply";
            observation: components["schemas"]["FactView"] | null;
            /**
             * Owner
             * @enum {string}
             */
            owner: "underwriter" | "producer" | "data_team";
        };
        /**
         * ChatExchange
         * @description An earlier message of the conversation and what it was answered with: the answer, a card's
         *     rationale or an error.
         */
        ChatExchange: {
            /** Message */
            message: string;
            /** Reply */
            reply: string;
        };
        /**
         * ChatRequest
         * @description One chat turn: the underwriter's message, the lead whose conversation is open when there is
         *     one, and the last exchanges of that conversation, oldest first.
         */
        ChatRequest: {
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatExchange"][];
            /** Lead Id */
            lead_id?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ChoiceReading
         * @description What the playbook makes of one value shown with an open choice; `problem` marks a value that
         *     fails the page or declines.
         */
        ChoiceReading: {
            /** Problem */
            problem: boolean;
            /** Text */
            text: string;
        };
        /**
         * Citation
         * @description What a reference number of one chat turn stands for. `id` is an event id for an `event`, for a
         *     `fact` (the event that recorded it) and for a `reply` (its `reply_received` event), an intent id
         *     for a `message`, and a page key for a `page`.
         */
        Citation: {
            /** Id */
            id: number | string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "event" | "fact" | "message" | "reply" | "page" | "lead";
            /** Lead Id */
            lead_id: string;
            /** Number */
            number: number;
            /** Text */
            text: string;
        };
        /** CommandResponse */
        CommandResponse: {
            /** Accepted */
            accepted: boolean;
            /** Event Id */
            event_id: number | null;
            /** Reason */
            reason: string | null;
        };
        /**
         * CoverageAdjustmentEffect
         * @description A proposed value for a coverage field; the submitted value stays with the facts.
         */
        CoverageAdjustmentEffect: {
            deadline: components["schemas"]["Deadline"] | null;
            /** Field */
            field: string;
            /** Proposed Value */
            proposed_value: string | number | boolean;
            /** Rule */
            rule: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "coverage_adjustment";
        };
        /**
         * Deadline
         * @enum {string}
         */
        Deadline: "within_60_days" | "first_term" | "underwriting_period" | "within_30_days_of_bind" | "duration_of_non_occupancy";
        /** DeclineEffect */
        DeclineEffect: {
            /** Rule */
            rule: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decline";
        };
        /** DeclineLeadCommand */
        DeclineLeadCommand: {
            payload: components["schemas"]["DeclineLeadPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decline_lead";
        };
        /** DeclineLeadPayload */
        DeclineLeadPayload: {
            /** Lead Id */
            lead_id: string;
            /** Reason */
            reason: string;
        };
        /** DeliverReplyCommand */
        DeliverReplyCommand: {
            payload: components["schemas"]["ReplyRequest"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deliver_reply";
        };
        /**
         * DraftView
         * @description One of the lead's intents (A.1). A reply is accepted only for one in state `sent`.
         */
        DraftView: {
            /** Body */
            body: string;
            /** Intent Id */
            intent_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "routine_request" | "sensitive_request" | "quote_packet" | "decline_notice";
            /** Payload Hash */
            payload_hash: string;
            /** Recipient */
            recipient: string;
            /** Round */
            round: number;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "dispatching" | "sent" | "unknown" | "closed_unsent";
            /** Subject */
            subject: string;
        };
        /** EditDraftCommand */
        EditDraftCommand: {
            payload: components["schemas"]["EditDraftPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "edit_draft";
        };
        /** EditDraftPayload */
        EditDraftPayload: {
            /** Body */
            body: string;
            /** Intent Id */
            intent_id: string;
            /** Reason */
            reason: string;
            /** Subject */
            subject: string;
        };
        /**
         * ErrorEvent
         * @description The turn closed without an answer.
         */
        ErrorEvent: {
            /** Reason */
            reason: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /**
         * EventMessage
         * @description The words of a sent request (subject and body) or of a received reply (body only).
         */
        EventMessage: {
            /** Body */
            body: string;
            /** Subject */
            subject: string | null;
        };
        /**
         * EventRow
         * @description One of a lead's events: its id, type, run mode, actor, simulated time and a summary of its payload.
         *     `item_id` is the underwriter's item a blocker or approval event names (a wait on the producer or on
         *     data is no item), `choice_ids` the choices a question card opened with or the one a ruling
         *     answers, `fact_key` the key a fact event records, `message` the words of a sent request or a
         *     reply, and `lookup` how a `provider_called` row's lookup went; each is None or empty where the
         *     event has none.
         */
        EventRow: {
            /**
             * Actor
             * @enum {string}
             */
            actor: "workflow" | "underwriter" | "assistant" | "inbound";
            /** Choice Ids */
            choice_ids: string[];
            /** Fact Key */
            fact_key: string | null;
            /** Id */
            id: number;
            /** Item Id */
            item_id: number | null;
            lookup: components["schemas"]["LookupView"] | null;
            message: components["schemas"]["EventMessage"] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "replay" | "record";
            /** Sim Ts */
            sim_ts: string;
            /** Summary */
            summary: string;
            type: components["schemas"]["EventType"];
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "run_started" | "replay_miss" | "draft_edited" | "proposal_created" | "lead_received" | "fact_observed" | "fact_selected" | "conflict_opened" | "conflict_closed" | "triage_completed" | "provider_called" | "plan_built" | "blocker_opened" | "blocker_closed" | "intent_created" | "message_sent" | "delivery_unknown" | "reply_received" | "reply_read" | "approval_recorded" | "ruling_recorded" | "command_refused" | "skill_fallback_used" | "model_called" | "fault_injected";
        /** ExclusionOrEndorsementEffect */
        ExclusionOrEndorsementEffect: {
            /** Rule */
            rule: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "exclusion_or_endorsement";
        };
        /**
         * FactField
         * @description A fact key an underwriter may resolve, with the label and answer type the page offers it by.
         */
        FactField: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Options */
            options: string[];
        };
        /**
         * FactView
         * @description An effective fact with its source tag. `p_f` is a fact like any other.
         */
        FactView: {
            /** Confirmed */
            confirmed: boolean;
            /** Event Id */
            event_id: number;
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Key */
            key: string;
            /** Observation Id */
            observation_id: number;
            /**
             * Source
             * @enum {string}
             */
            source: "submitted" | "fetched" | "derived" | "assumed" | "reply" | "underwriter";
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "pending_review" | "rejected";
            value: components["schemas"]["JsonValue"];
        };
        /** FixtureRepliesResponse */
        FixtureRepliesResponse: {
            /** Replies */
            replies: components["schemas"]["ReplyResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Item
         * @description An open item an underwriter acts on: a review, a question card or an unknown delivery. The
         *     lead's detail carries what its action needs; this row says which lead to open.
         */
        Item: {
            detail: components["schemas"]["BlockerDetail"];
            /** Item Id */
            item_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "delivery_unknown" | "underwriter_question" | "underwriter_review" | "data" | "producer_reply";
            /** Lead Id */
            lead_id: string;
        };
        JsonValue: unknown;
        /**
         * LeadDetail
         * @description `GET /api/leads/{id}`. The rule traces are the plan's (`effects[].trace`,
         *     `declines_on_every_branch`); its open choices and `not_evaluated` notes are the plan's too.
         */
        LeadDetail: {
            /** Blockers */
            blockers: components["schemas"]["BlockerView"][];
            /** Drafts */
            drafts: components["schemas"]["DraftView"][];
            /** Facts */
            facts: components["schemas"]["FactView"][];
            /** Fields */
            fields: components["schemas"]["FactField"][];
            /** Label */
            label: string;
            /** Lead Id */
            lead_id: string;
            /** Pages */
            pages: components["schemas"]["PlanPage"][];
            plan: components["schemas"]["ActionPlan"] | null;
            /** Readings */
            readings: {
                [key: string]: {
                    [key: string]: components["schemas"]["ChoiceReading"];
                };
            };
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "triaged" | "in_progress" | "quote_sent" | "declined";
            /** Summary */
            summary: string;
        };
        /** LeadEvents */
        LeadEvents: {
            /** Events */
            events: components["schemas"]["EventRow"][];
            /** Lead Id */
            lead_id: string;
        };
        /**
         * LookupView
         * @description How a provider lookup went: its status and, when blocked, the inputs it lacked.
         */
        LookupView: {
            /** Missing Inputs */
            missing_inputs: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "found" | "not_found" | "blocked" | "unavailable";
        };
        /** NoActionEffect */
        NoActionEffect: {
            /** Rule */
            rule: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "no_action";
        };
        /** NotEvaluatedNote */
        NotEvaluatedNote: {
            /** Producer Text */
            producer_text: string;
            /** Ref */
            ref: string;
            /** Text */
            text: string;
        };
        /**
         * ObligationEffect
         * @description A post-bind obligation; recorded and never executed.
         */
        ObligationEffect: {
            /** Rule */
            rule: string;
            /** Text */
            text: string;
            /** Trigger */
            trigger: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "obligation";
        };
        /** OpenChoice */
        OpenChoice: {
            /** Choice Id */
            choice_id: string;
            /** Options */
            options: string[];
            /** Prompt */
            prompt: string;
            /** Show */
            show: string[];
        };
        /**
         * PlanPage
         * @description What the lead's stored plan holds for one playbook page.
         */
        PlanPage: {
            /** Declines On Every Branch */
            declines_on_every_branch: components["schemas"]["RuleTrace"][];
            /** Effects */
            effects: components["schemas"]["PlannedEffect"][];
            /** Key */
            key: string;
            /** Not Evaluated */
            not_evaluated: components["schemas"]["NotEvaluatedNote"][];
            /** Waits On */
            waits_on: string[];
        };
        /** PlannedEffect */
        PlannedEffect: {
            /** Committed */
            committed: boolean;
            /** Effect */
            effect: components["schemas"]["DeclineEffect"] | components["schemas"]["RequirementEffect"] | components["schemas"]["SurchargeEffect"] | components["schemas"]["ExclusionOrEndorsementEffect"] | components["schemas"]["CoverageAdjustmentEffect"] | components["schemas"]["AdvisoryEffect"] | components["schemas"]["ObligationEffect"] | components["schemas"]["NoActionEffect"];
            trace: components["schemas"]["RuleTrace"];
        };
        /**
         * ProposalEvent
         * @description The turn closed with a card: `GET /api/proposals` holds it.
         */
        ProposalEvent: {
            /** Lead Id */
            lead_id: string | null;
            /** Proposal Id */
            proposal_id: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "proposal";
        };
        /**
         * ProposalView
         * @description A proposal card (A.1). A command proposal's payload is `{type, payload, rationale}`.
         */
        ProposalView: {
            /** Lead Id */
            lead_id: string | null;
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Proposal Id */
            proposal_id: number;
        };
        /**
         * QueueRow
         * @description One row per lead, in the order the response lists them. The one-sentence summary is
         *     `GET /api/run`'s `summary`, not part of this response.
         */
        QueueRow: {
            /** Age Business Days */
            age_business_days: number;
            /** Ask Count */
            ask_count: number;
            /** Effective Date */
            effective_date: string | null;
            /**
             * Group
             * @enum {string}
             */
            group: "blocked_on_underwriter" | "waiting_on_data_or_producer" | "finished";
            /** Label */
            label: string;
            /** Lead Id */
            lead_id: string;
            /** Primary Next Action */
            primary_next_action: ("delivery_unknown" | "underwriter_question" | "underwriter_review" | "data" | "producer_reply") | null;
            /** Service Level Breached */
            service_level_breached: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "triaged" | "in_progress" | "quote_sent" | "declined";
            /** Waits On */
            waits_on: ("underwriter" | "producer" | "data_team") | null;
        };
        /** RecordRulingCommand */
        RecordRulingCommand: {
            payload: components["schemas"]["RecordRulingPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record_ruling";
        };
        /** RecordRulingPayload */
        RecordRulingPayload: {
            /** Choice Id */
            choice_id: string;
            /** Lead Id */
            lead_id: string;
            /** Option */
            option: string;
            /** Reason */
            reason: string;
        };
        /** RejectCommand */
        RejectCommand: {
            payload: components["schemas"]["RejectPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reject";
        };
        /** RejectPayload */
        RejectPayload: {
            /** Item Id */
            item_id: number;
            /** Reason */
            reason: string;
        };
        /**
         * ReplyRequest
         * @description `POST /api/replies` and the `deliver_reply` payload; the body is capped at `MAX_BODY_CHARACTERS` (A.9).
         */
        ReplyRequest: {
            /** Body */
            body: string;
            /** Intent Id */
            intent_id: string;
            /** Lead Id */
            lead_id: string;
        };
        /**
         * ReplyResponse
         * @description Returned after the reply has been read and the lead re-evaluated, or refused.
         */
        ReplyResponse: {
            /** Accepted */
            accepted: boolean;
            /** Event Id */
            event_id: number | null;
            /** Lead Id */
            lead_id: string;
            /** Reason */
            reason: string | null;
        };
        /** RequirementEffect */
        RequirementEffect: {
            deadline: components["schemas"]["Deadline"] | null;
            /** Rule */
            rule: string;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "requirement";
        };
        /** ResolveFactCommand */
        ResolveFactCommand: {
            payload: components["schemas"]["ResolveFactPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resolve_fact";
        };
        /** ResolveFactPayload */
        ResolveFactPayload: {
            /** Key */
            key: string;
            /** Lead Id */
            lead_id: string;
            /** Reason */
            reason: string;
            /** Value */
            value: string | number | boolean;
        };
        /**
         * RuleTrace
         * @description Either one path or a set of alternatives, never both.
         */
        RuleTrace: {
            /**
             * Alternatives
             * @default []
             */
            alternatives: components["schemas"]["TraceBranch"][];
            /** Board Path */
            board_path: string[];
            /**
             * Choice Ids
             * @default []
             */
            choice_ids: string[];
        };
        /**
         * RunSummary
         * @description The one-sentence summary's seven counts (section 11).
         *
         *     `follow_ups_sent` counts every request sent to a producer, in any round. The four waiting
         *     counts count each lead once, by its primary next action: an underwriter review or question, a
         *     producer reply, a data blocker, or an unknown delivery.
         */
        RunSummary: {
            /** Declines Approved */
            declines_approved: number;
            /** Delivery Unknown */
            delivery_unknown: number;
            /** Follow Ups Sent */
            follow_ups_sent: number;
            /** Quotes Sent */
            quotes_sent: number;
            /** Waiting On Data */
            waiting_on_data: number;
            /** Waiting On Producer */
            waiting_on_producer: number;
            /** Waiting On Underwriter */
            waiting_on_underwriter: number;
        };
        /**
         * RunView
         * @description `GET /api/run`; also the reply of `POST /api/run/start`. Before a run starts `run_id` and
         *     `sim_now` are null and the counts are zero.
         */
        RunView: {
            /** Example Prompts */
            example_prompts: string[];
            /** First Pass Complete */
            first_pass_complete: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "replay" | "record";
            /** Run Id */
            run_id: string | null;
            /** Seed */
            seed: number;
            /** Sim Now */
            sim_now: string | null;
            summary: components["schemas"]["RunSummary"];
        };
        /** StartRunCommand */
        StartRunCommand: {
            payload: components["schemas"]["StartRunPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "start_run";
        };
        /** StartRunPayload */
        StartRunPayload: {
            /** Seed */
            seed: number;
        };
        /**
         * StepEvent
         * @description A lookup of the turn has completed: what was read and what it held, in one line.
         */
        StepEvent: {
            /** Summary */
            summary: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /** SurchargeEffect */
        SurchargeEffect: {
            deadline: components["schemas"]["Deadline"] | null;
            /** Percent */
            percent: number;
            /** Rule */
            rule: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "surcharge";
        };
        /**
         * TraceBranch
         * @description One alternative of a decline on every branch: the cases taken for the unknown inputs and the path that follows.
         */
        TraceBranch: {
            /** Assumed */
            assumed: components["schemas"]["Assumption"][];
            /** Board Path */
            board_path: string[];
            /** Rule */
            rule: string;
        };
        /** UndecidedPage */
        UndecidedPage: {
            /** Graph */
            graph: string;
            /** Waits On */
            waits_on: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_command_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveCommand"] | components["schemas"]["RejectCommand"] | components["schemas"]["EditDraftCommand"] | components["schemas"]["RecordRulingCommand"] | components["schemas"]["ResolveFactCommand"] | components["schemas"]["DeclineLeadCommand"] | components["schemas"]["DeliverReplyCommand"] | components["schemas"]["StartRunCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
        };
    };
    list_leads_api_leads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueRow"][];
                };
            };
        };
    };
    get_lead_api_leads__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_events_api_leads__id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadEvents"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalView"][];
                };
            };
        };
    };
    apply_proposal_api_proposals__proposal_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_proposal_api_proposals__proposal_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_reply_api_replies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_fixture_replies_api_replies_fixtures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureRepliesResponse"];
                };
            };
        };
    };
    get_run_api_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
        };
    };
    start_run_api_run_start_post: {
        parameters: {
            query?: {
                wait?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
